### PR TITLE
Update ITV2,3 and 4

### PR DESCRIPTION
**Pull request by krisawatson**
Change HD to SD

### CODE REVIEW

**Comment by davesayers2014** [comment]
SD is still FTA so why change it with cable. So is HD definitely not clearing on Sat?

**Comment by krisawatson** [comment]
Made the change you suggested as in swap out the Sat SD versions of the ITV channels the pull request should be updated

**Comment by davesayers2014** [comment]
I'll review this at some point but they are still clearing on Sat just some bad cache issues at the moment. If needed I'll swap them for cable HD channels rather than having 2 SD versions.

**Comment by Huevos** [comment]
HD versions require a subscription card, but do clear.

**Pull request closed without merging**
